[project]
name = "storey-allocator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "colorama==0.4.6",
    "compas==2.14.1",
    "cwapi3d==32.299.0",
]
